workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-s3-sync

pipeline:
  build:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - make vet
      - make build
      - make test

  docker:
    repo: plugins/drone-s3-sync
    tag: latest
    when:
      branch: master
      event: push

plugin:
  name: S3 Sync
  desc: Sync a directory with an Amazon S3 Bucket
  type: publish
  image: plugins/drone-s3-sync
  labels:
    - publish
    - artifacts
    - amazon
    - aws
    - s3
