build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-s3-sync
    tag: native
    when:
      branch: native

plugin:
  name: S3 Sync
  desc: Syncs a directory with an Amazon S3 Bucket
  type: publish
  image: plugins/drone-s3-sync
  labels:
    - publish
    - artifacts
    - amazon
    - aws
    - s3
