workspace:
  path: src/github.com/drone-plugins/drone-s3-sync
  base: /go

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  publish:
    image: plugins/docker
    repo: plugins/s3-sync
    tags: [ "latest", "1.1", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: S3 Sync
  desc: Sync a directory with an Amazon S3 Bucket
  type: publish
  image: plugins/s3-sync
  labels:
    - publish
    - artifacts
    - amazon
    - aws
    - s3
